on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build vue app
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: true # Disable automatic npm caching if not required
      - run: npm ci
      - run: npm run build-only

      - name: Sync Files
        uses: milanmk/actions-file-deployer@1.18
        with:
          #sync: "full"
          remote-protocol: "ftp"
          remote-port: "21"
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: "/"
          local-path: "./dist/"